<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Antraege\SperrmuellAntragDetail.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Home\Contracts\" />
    <Folder Include="wwwroot\lib\daypilot\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Antraege\SperrmuellAntragDetail.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.10" />
  </ItemGroup>

</Project>
