<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuergerPortal.Application\BuergerPortal.Application.csproj" />
    <ProjectReference Include="..\BuergerPortal.Domain\BuergerPortal.Domain.csproj" />
  </ItemGroup>

</Project>
