# ========= Runtime (final) =========
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

# ========= Build =========
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# ganzen Code in den Build-Container kopieren
COPY . .

# Auth-Server Projekt RESTOREN (Pfad/Name anpassen falls nötig)
RUN dotnet restore "AuthenticationServer/AuthenticationServer.csproj"

# Publish
WORKDIR "/src/AuthenticationServer"
RUN dotnet publish "AuthenticationServer.csproj" -c Release -o /app/publish /p:UseAppHost=false

# ========= Final Image =========
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "AuthenticationServer.dll"]
