// <auto-generated />
using System;
using BuergerPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuergerPortal.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20251104145115_Add_Antrag")]
    partial class Add_Antrag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuergerPortal.Domain.Antrag.Entity.Antrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId", "Typ", "Status");

                    b.ToTable("Antraege", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BuergerPortal.Domain.Appointments.Entity.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AntragId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AntragId");

                    b.HasIndex("Service", "StartUtc", "EndUtc");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Antrag.Entity.ReisepassAntrag", b =>
                {
                    b.HasBaseType("BuergerPortal.Domain.Antrag.Entity.Antrag");

                    b.Property<bool>("AltpassVorhanden")
                        .HasColumnType("bit");

                    b.Property<bool>("Express")
                        .HasColumnType("bit");

                    b.Property<string>("Hinweis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.ToTable("ReisepassAntraege", (string)null);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Appointments.Entity.Appointment", b =>
                {
                    b.HasOne("BuergerPortal.Domain.Antrag.Entity.Antrag", null)
                        .WithMany()
                        .HasForeignKey("AntragId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Antrag.Entity.ReisepassAntrag", b =>
                {
                    b.HasOne("BuergerPortal.Domain.Antrag.Entity.Antrag", null)
                        .WithOne()
                        .HasForeignKey("BuergerPortal.Domain.Antrag.Entity.ReisepassAntrag", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.Kontakt", "Kontakt", b1 =>
                        {
                            b1.Property<Guid>("ReisepassAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.Property<string>("Telefon")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Telefon");

                            b1.HasKey("ReisepassAntragId");

                            b1.ToTable("ReisepassAntraege");

                            b1.WithOwner()
                                .HasForeignKey("ReisepassAntragId");
                        });

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.PersonBirth", "Birth", b1 =>
                        {
                            b1.Property<Guid>("ReisepassAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Geburtsdatum")
                                .HasColumnType("date")
                                .HasColumnName("Geburtsdatum");

                            b1.HasKey("ReisepassAntragId");

                            b1.ToTable("ReisepassAntraege");

                            b1.WithOwner()
                                .HasForeignKey("ReisepassAntragId");
                        });

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ReisepassAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nachname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nachname");

                            b1.Property<string>("Vorname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Vorname");

                            b1.HasKey("ReisepassAntragId");

                            b1.ToTable("ReisepassAntraege");

                            b1.WithOwner()
                                .HasForeignKey("ReisepassAntragId");
                        });

                    b.Navigation("Birth")
                        .IsRequired();

                    b.Navigation("Kontakt")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
