// <auto-generated />
using System;
using BuergerPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuergerPortal.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20260106151450_AddPoiTable")]
    partial class AddPoiTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuergerPortal.Domain.Antrag.Entity.Antrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId", "Typ", "Status");

                    b.ToTable("Antraege", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BuergerPortal.Domain.Appointments.Entity.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AntragId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AntragId");

                    b.HasIndex("Service", "StartUtc", "EndUtc");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Maengel.Maengelmeldung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressHint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("ReporterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("Status");

                    b.ToTable("Maengelmeldungen", (string)null);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Poi.Entity.PoiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Pois", (string)null);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Settings.Entity.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowGeolocation")
                        .HasColumnType("bit");

                    b.Property<bool>("AnalyticsOptIn")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("ReduceDataUsage")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Antrag.Entity.ReisepassAntrag", b =>
                {
                    b.HasBaseType("BuergerPortal.Domain.Antrag.Entity.Antrag");

                    b.Property<bool>("AltpassVorhanden")
                        .HasColumnType("bit");

                    b.Property<bool>("Express")
                        .HasColumnType("bit");

                    b.Property<string>("Hinweis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.ToTable("ReisepassAntraege", (string)null);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Antrag.Entity.SperrmuellAntrag", b =>
                {
                    b.HasBaseType("BuergerPortal.Domain.Antrag.Entity.Antrag");

                    b.Property<string>("Hinweis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Wunschzeit")
                        .HasColumnType("datetime2");

                    b.ToTable("SperrmuellAntraege", (string)null);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Appointments.Entity.Appointment", b =>
                {
                    b.HasOne("BuergerPortal.Domain.Antrag.Entity.Antrag", null)
                        .WithMany()
                        .HasForeignKey("AntragId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BuergerPortal.Domain.Antrag.Entity.ReisepassAntrag", b =>
                {
                    b.HasOne("BuergerPortal.Domain.Antrag.Entity.Antrag", null)
                        .WithOne()
                        .HasForeignKey("BuergerPortal.Domain.Antrag.Entity.ReisepassAntrag", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.PersonBirth", "Birth", b1 =>
                        {
                            b1.Property<Guid>("ReisepassAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Geburtsdatum")
                                .HasColumnType("date")
                                .HasColumnName("Geburtsdatum");

                            b1.HasKey("ReisepassAntragId");

                            b1.ToTable("ReisepassAntraege");

                            b1.WithOwner()
                                .HasForeignKey("ReisepassAntragId");
                        });

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.Kontakt", "Kontakt", b1 =>
                        {
                            b1.Property<Guid>("ReisepassAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.Property<string>("Telefon")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Telefon");

                            b1.HasKey("ReisepassAntragId");

                            b1.ToTable("ReisepassAntraege");

                            b1.WithOwner()
                                .HasForeignKey("ReisepassAntragId");
                        });

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ReisepassAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nachname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nachname");

                            b1.Property<string>("Vorname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Vorname");

                            b1.HasKey("ReisepassAntragId");

                            b1.ToTable("ReisepassAntraege");

                            b1.WithOwner()
                                .HasForeignKey("ReisepassAntragId");
                        });

                    b.Navigation("Birth")
                        .IsRequired();

                    b.Navigation("Kontakt")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("BuergerPortal.Domain.Antrag.Entity.SperrmuellAntrag", b =>
                {
                    b.HasOne("BuergerPortal.Domain.Antrag.Entity.Antrag", null)
                        .WithOne()
                        .HasForeignKey("BuergerPortal.Domain.Antrag.Entity.SperrmuellAntrag", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.PersonBirth", "Birth", b1 =>
                        {
                            b1.Property<Guid>("SperrmuellAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Geburtsdatum")
                                .HasColumnType("date")
                                .HasColumnName("Geburtsdatum");

                            b1.HasKey("SperrmuellAntragId");

                            b1.ToTable("SperrmuellAntraege");

                            b1.WithOwner()
                                .HasForeignKey("SperrmuellAntragId");
                        });

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.Kontakt", "Kontakt", b1 =>
                        {
                            b1.Property<Guid>("SperrmuellAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.Property<string>("Telefon")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Telefon");

                            b1.HasKey("SperrmuellAntragId");

                            b1.ToTable("SperrmuellAntraege");

                            b1.WithOwner()
                                .HasForeignKey("SperrmuellAntragId");
                        });

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SperrmuellAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nachname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nachname");

                            b1.Property<string>("Vorname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Vorname");

                            b1.HasKey("SperrmuellAntragId");

                            b1.ToTable("SperrmuellAntraege");

                            b1.WithOwner()
                                .HasForeignKey("SperrmuellAntragId");
                        });

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.Addresse", "Addresse", b1 =>
                        {
                            b1.Property<Guid>("SperrmuellAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ort");

                            b1.Property<string>("PLZ")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PLZ");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Strasse");

                            b1.HasKey("SperrmuellAntragId");

                            b1.ToTable("SperrmuellAntraege");

                            b1.WithOwner()
                                .HasForeignKey("SperrmuellAntragId");
                        });

                    b.OwnsOne("BuergerPortal.Domain.Antrag.ValueObjects.SperrmuellMengen", "Mengen", b1 =>
                        {
                            b1.Property<Guid>("SperrmuellAntragId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("HolzKubikmeter")
                                .HasColumnType("int")
                                .HasColumnName("HolzKubikmeter");

                            b1.Property<int?>("Matratzen")
                                .HasColumnType("int")
                                .HasColumnName("Matratzen");

                            b1.Property<int?>("SonstigesKubikmeter")
                                .HasColumnType("int")
                                .HasColumnName("SonstigesKubikmeter");

                            b1.HasKey("SperrmuellAntragId");

                            b1.ToTable("SperrmuellAntraege");

                            b1.WithOwner()
                                .HasForeignKey("SperrmuellAntragId");
                        });

                    b.Navigation("Addresse")
                        .IsRequired();

                    b.Navigation("Birth")
                        .IsRequired();

                    b.Navigation("Kontakt")
                        .IsRequired();

                    b.Navigation("Mengen")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
